#!/usr/bin/env bash
# Script that displays information about subdomains of a given domain

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local result
    local record_type
    local destination

    result=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION:/{getline; print}')
    record_type=$(echo $result | awk '{print $4}')
    destination=$(echo $result | awk '{print $5}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" $subdomain
fi
